name = "MaGe"
uuid = "a1237f97-e57a-43a8-8ead-9081d93d2731"
authors = ["Paul Nemec"]
version = "0.3.1"

[deps]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.5"
