name = "MaGe"
uuid = "a1237f97-e57a-43a8-8ead-9081d93d2731"
authors = ["Paul Nemec"]
version = "0.2.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
